### ISSUE TITLE
contact form configuration

### ISSUE THREAD

**Issue by danaron** [mittwald/neos-onepageagency#6]
HI Philipp,
Nice work. Like it. I am new to neos, therefore having problems to configure the contact form. Is it made with the Flow Form Framework? Where can I configure the E-Mail, where the form is sent to?
Thanks for your help.
Best regards
Dan

**Comment by twiesing** [comment]
Hey,

the Site Package is only a startpoint for further developments.

Contact Forms are not implemented yet.

Simple contact forms are made like here: http://neos.readthedocs.io/en/stable/HowTos/AddingSimpleContactForm.html

- Tobi
